USE [master]
GO

/****** Object:  Database [RegFieldTrials]    Script Date: 02/05/2015 09:33:46 ******/
CREATE DATABASE [RegFieldTrials] ON  PRIMARY 
( NAME = N'RegFieldDataCollection', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\RegFieldTrials.mdf' , SIZE = 51200KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'RegFieldDataCollection_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\RegFieldTrials_log.ldf' , SIZE = 51200KB , MAXSIZE = UNLIMITED , FILEGROWTH = 10%)
GO

ALTER DATABASE [RegFieldTrials] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RegFieldTrials].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [RegFieldTrials] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [RegFieldTrials] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [RegFieldTrials] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [RegFieldTrials] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [RegFieldTrials] SET ARITHABORT OFF 
GO

ALTER DATABASE [RegFieldTrials] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [RegFieldTrials] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [RegFieldTrials] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [RegFieldTrials] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [RegFieldTrials] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [RegFieldTrials] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [RegFieldTrials] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [RegFieldTrials] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [RegFieldTrials] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [RegFieldTrials] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [RegFieldTrials] SET  DISABLE_BROKER 
GO

ALTER DATABASE [RegFieldTrials] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [RegFieldTrials] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [RegFieldTrials] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [RegFieldTrials] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [RegFieldTrials] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [RegFieldTrials] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [RegFieldTrials] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [RegFieldTrials] SET  READ_WRITE 
GO

ALTER DATABASE [RegFieldTrials] SET RECOVERY FULL 
GO

ALTER DATABASE [RegFieldTrials] SET  MULTI_USER 
GO

ALTER DATABASE [RegFieldTrials] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [RegFieldTrials] SET DB_CHAINING OFF 
GO

-- Create User
USE [RegFieldTrials]
GO
CREATE USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G] FOR LOGIN [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
CREATE USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G] FOR LOGIN [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
CREATE USER [NORTH_AMERICA\NA1000App_fidosync] FOR LOGIN [NORTH_AMERICA\NA1000App_fidosync]
CREATE USER [NORTH_AMERICA\NA1000APP-FIDO2-P] FOR LOGIN [NORTH_AMERICA\NA1000APP-FIDO2-P]
CREATE USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
CREATE USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]
GO

-- Add users to specific database role.
USE [RegFieldTrials]
GO
EXEC sp_addrolemember N'db_datareader' , N'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember N'db_datawriter' , N'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G'

EXEC sp_addrolemember N'db_datareader' , N'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember N'db_datawriter' , N'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G'

EXEC sp_addrolemember N'db_datareader' , N'NORTH_AMERICA\NA1000App_fidosync'
EXEC sp_addrolemember N'db_datawriter' , N'NORTH_AMERICA\NA1000App_fidosync'

EXEC sp_addrolemember N'db_datareader' , N'NORTH_AMERICA\NA1000APP-FIDO2-P'
EXEC sp_addrolemember N'db_datawriter' , N'NORTH_AMERICA\NA1000APP-FIDO2-P'

EXEC sp_addrolemember N'db_datareader' , N'NORTH_AMERICA\NA-1000-FIDO_DEVL-L'
EXEC sp_addrolemember N'db_datawriter' , N'NORTH_AMERICA\NA-1000-FIDO_DEVL-L'

EXEC sp_addrolemember N'db_datareader' , N'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G'
EXEC sp_addrolemember N'db_datawriter' , N'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G'

EXEC sp_addrolemember N'db_datareader' , N'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G'
EXEC sp_addrolemember N'db_datawriter' , N'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G'

EXEC sp_addrolemember N'db_datareader' , N'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G'
EXEC sp_addrolemember N'db_datawriter' , N'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G'
EXEC sp_addrolemember N'db_owner' , N'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G'
GO










