//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class SRR_EvalResponse
    {
        public int EvalResponse_ID { get; set; }
        public int SRR_ID { get; set; }
        public Nullable<int> YearsExperience_SRR { get; set; }
        public Nullable<int> YearsExperience_SiteLeadSRR { get; set; }
        public Nullable<int> NumFieldsReponsibleFor { get; set; }
        public Nullable<decimal> NumAcresSRRManages { get; set; }
        public Nullable<bool> BackupSRRIdentified { get; set; }
        public Nullable<int> BackupSRR_ID { get; set; }
        public Nullable<bool> BackupSRRInformed { get; set; }
        public Nullable<bool> ComplianceQuestion1 { get; set; }
        public Nullable<bool> ComplianceQuestion2 { get; set; }
        public Nullable<bool> ComplianceQuestion3 { get; set; }
        public Nullable<bool> ComplianceQuestion4 { get; set; }
        public Nullable<bool> ComplianceQuestion5 { get; set; }
        public Nullable<bool> ComplianceQuestion6 { get; set; }
        public Nullable<bool> Flagged { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<int> CompletedYear { get; set; }
        public string ComplianceResponse1 { get; set; }
        public string ComplianceResponse2 { get; set; }
        public string ComplianceResponse3 { get; set; }
        public string ComplianceResponse4 { get; set; }
        public string ComplianceResponse5 { get; set; }
        public string ComplianceResponse6 { get; set; }
        public Nullable<int> LastTrainingYear { get; set; }
    
        public virtual User User { get; set; }
    }
}
