//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialCatalog
    {
        public TrialCatalog()
        {
            this.TrialProgresses = new HashSet<TrialProgress>();
            this.TrialWorkflowAttachments = new HashSet<TrialWorkflowAttachment>();
            this.SRRUser_Trial_Xref = new HashSet<SRRUser_Trial_Xref>();
            this.TrialNotes = new HashSet<TrialNote>();
        }
    
        public int Trial_ID { get; set; }
        public int SRRLeadUser_ID { get; set; }
        public Nullable<int> IRPUser_ID { get; set; }
        public int Crop_ID { get; set; }
        public Nullable<int> Trait_ID { get; set; }
        public Nullable<int> Site_ID { get; set; }
        public Nullable<int> TrialYear { get; set; }
        public string AgencyApprovalNo { get; set; }
        public string Name { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string County { get; set; }
        public string FarmName { get; set; }
        public Nullable<bool> Internal { get; set; }
        public Nullable<decimal> GPSLat1 { get; set; }
        public Nullable<decimal> GPSLong1 { get; set; }
        public Nullable<decimal> GPSLat2 { get; set; }
        public Nullable<decimal> GPSLong2 { get; set; }
        public Nullable<decimal> GPSLat3 { get; set; }
        public Nullable<decimal> GPSLong3 { get; set; }
        public Nullable<decimal> GPSLat4 { get; set; }
        public Nullable<decimal> GPSLong4 { get; set; }
        public Nullable<decimal> Approved_Area { get; set; }
        public Nullable<int> Approved_Area_UOM { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public bool Archive { get; set; }
        public string ComplianceStatus { get; set; }
    
        public virtual Crop Crop { get; set; }
        public virtual SiteMaster SiteMaster { get; set; }
        public virtual TraitMaster TraitMaster { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        public virtual ICollection<TrialProgress> TrialProgresses { get; set; }
        public virtual ICollection<TrialWorkflowAttachment> TrialWorkflowAttachments { get; set; }
        public virtual ICollection<SRRUser_Trial_Xref> SRRUser_Trial_Xref { get; set; }
        public virtual ICollection<TrialNote> TrialNotes { get; set; }
    }
}
