//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialWorkflowAttachment
    {
        public System.Guid Attachment_ID { get; set; }
        public int Trial_ID { get; set; }
        public int Workflow_ID { get; set; }
        public string AttachmentName { get; set; }
        public byte[] Attachment { get; set; }
        public int AttachmentType_ID { get; set; }
        public string Comment { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual AttachmentType AttachmentType { get; set; }
        public virtual TrialCatalog TrialCatalog { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
