//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.TrialCatalogs = new HashSet<TrialCatalog>();
            this.TrialCatalogs1 = new HashSet<TrialCatalog>();
            this.TrialProgresses = new HashSet<TrialProgress>();
            this.User1 = new HashSet<User>();
            this.SRR_EvalResponse = new HashSet<SRR_EvalResponse>();
            this.SRRUser_Trial_Xref = new HashSet<SRRUser_Trial_Xref>();
        }
    
        public int User_ID { get; set; }
        public int UserType_ID { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Email { get; set; }
        public string OfficeNumber { get; set; }
        public string CellNumber { get; set; }
        public string SiteLocation { get; set; }
        public Nullable<int> Manager_ID { get; set; }
        public Nullable<bool> Internal { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public string UserAlias { get; set; }
    
        public virtual ICollection<TrialCatalog> TrialCatalogs { get; set; }
        public virtual ICollection<TrialCatalog> TrialCatalogs1 { get; set; }
        public virtual ICollection<TrialProgress> TrialProgresses { get; set; }
        public virtual ICollection<User> User1 { get; set; }
        public virtual User User2 { get; set; }
        public virtual UserType UserType { get; set; }
        public virtual ICollection<SRR_EvalResponse> SRR_EvalResponse { get; set; }
        public virtual ICollection<SRRUser_Trial_Xref> SRRUser_Trial_Xref { get; set; }
    }
}
