//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class v_UserTrials
    {
        public int Trial_ID { get; set; }
        public string Name { get; set; }
        public int PrimarySRR { get; set; }
        public string UserTypeName { get; set; }
        public int User_ID { get; set; }
        public string LName { get; set; }
        public string FName { get; set; }
        public string UserAlias { get; set; }
        public int UserType_ID { get; set; }
    }
}
