//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.Common.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowQuestion
    {
        public int WorkflowQuestion_ID { get; set; }
        public int Workflow_ID { get; set; }
        public int Question_ID { get; set; }
        public string AcceptableAnswers { get; set; }
        public Nullable<int> AcceptableLowRange { get; set; }
        public Nullable<int> AcceptableHighRange { get; set; }
        public string NotAcceptableAnswers { get; set; }
        public Nullable<int> NotAcceptableLowRange { get; set; }
        public Nullable<int> NotAcceptableHighRange { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
