//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Question
    {
        public Question()
        {
            this.Responses = new HashSet<Response>();
            this.WorkflowQuestions = new HashSet<WorkflowQuestion>();
        }
    
        public int Question_ID { get; set; }
        public string QuestionName { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public string QuestionText { get; set; }
        public bool IsLookup { get; set; }
    
        public virtual ICollection<Response> Responses { get; set; }
        public virtual ICollection<WorkflowQuestion> WorkflowQuestions { get; set; }
    }
}
