//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Response
    {
        public System.Guid Response_ID { get; set; }
        public int Question_ID { get; set; }
        public int TrialProgress_ID { get; set; }
        public string ResponseValue { get; set; }
        public Nullable<bool> FollowupRequired { get; set; }
        public Nullable<System.DateTime> VerifiedDate { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual Question Question { get; set; }
        public virtual TrialProgress TrialProgress { get; set; }
    }
}
