//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FIDOVictory.AdminTool.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrialProgress
    {
        public TrialProgress()
        {
            this.Responses = new HashSet<Response>();
        }
    
        public int TrialProgress_ID { get; set; }
        public int Trial_ID { get; set; }
        public int SRRUser_ID { get; set; }
        public Nullable<int> Workflow_ID { get; set; }
        public Nullable<bool> WorkflowComplete { get; set; }
        public Nullable<System.DateTime> WorkflowCompleteDate { get; set; }
        public System.DateTime UpdateDateTime { get; set; }
        public string UpdateUserID { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual ICollection<Response> Responses { get; set; }
        public virtual TrialCatalog TrialCatalog { get; set; }
        public virtual User User { get; set; }
        public virtual Workflow Workflow { get; set; }
    }
}
