-- this is current permissions in test as of 3/11.
use regfieldtrials
go
-- drop users
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G') DROP USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G') DROP USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L') DROP USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-VICT-SUPPORT-G') DROP USER [NORTH_AMERICA\NA-1000-VICT-SUPPORT-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-VICT_RPTUSER-G') DROP USER [NORTH_AMERICA\NA-1000-VICT_RPTUSER-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000APP-FIDO2-P') DROP USER [NORTH_AMERICA\NA1000APP-FIDO2-P]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000App_fidosync') DROP USER [NORTH_AMERICA\NA1000App_fidosync]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G') DROP USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G') DROP USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L') DROP USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000APP-FIDO2-P') DROP USER [NORTH_AMERICA\NA1000APP-FIDO2-P]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000App_fidosync') DROP USER [NORTH_AMERICA\NA1000App_fidosync]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G') DROP USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G') DROP USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L') DROP USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000APP-FIDO2-P') DROP USER [NORTH_AMERICA\NA1000APP-FIDO2-P]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000App_fidosync') DROP USER [NORTH_AMERICA\NA1000App_fidosync]
IF  EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G') DROP USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]

use regfieldtrials
go
-- create users
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G')  CREATE USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G] FOR LOGIN [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G')  CREATE USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G] FOR LOGIN [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000App_fidosync')  CREATE USER [NORTH_AMERICA\NA1000App_fidosync] FOR LOGIN [NORTH_AMERICA\NA1000App_fidosync]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000APP-FIDO2-P')  CREATE USER [NORTH_AMERICA\NA1000APP-FIDO2-P] FOR LOGIN [NORTH_AMERICA\NA1000APP-FIDO2-P]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-VICT-SUPPORT-G')  CREATE USER [NORTH_AMERICA\NA-1000-VICT-SUPPORT-G] FOR LOGIN [NORTH_AMERICA\NA-1000-VICT-SUPPORT-G]
IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-VICT_RPTUSER-G')  CREATE USER [NORTH_AMERICA\NA-1000-VICT_RPTUSER-G] FOR LOGIN [NORTH_AMERICA\NA-1000-VICT_RPTUSER-G]

--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G')  CREATE USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G] FOR LOGIN [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G')  CREATE USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G] FOR LOGIN [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000APP-FIDO2-P')  CREATE USER [NORTH_AMERICA\NA1000APP-FIDO2-P] FOR LOGIN [NORTH_AMERICA\NA1000APP-FIDO2-P]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000App_fidosync')  CREATE USER [NORTH_AMERICA\NA1000App_fidosync] FOR LOGIN [NORTH_AMERICA\NA1000App_fidosync]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G')  CREATE USER [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G] FOR LOGIN [ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G')  CREATE USER [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G] FOR LOGIN [LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APP-Q-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO_DEVL-L] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO_DEVL-L]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000APP-FIDO2-P')  CREATE USER [NORTH_AMERICA\NA1000APP-FIDO2-P] FOR LOGIN [NORTH_AMERICA\NA1000APP-FIDO2-P]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA1000App_fidosync')  CREATE USER [NORTH_AMERICA\NA1000App_fidosync] FOR LOGIN [NORTH_AMERICA\NA1000App_fidosync]
--IF  NOT EXISTS (SELECT * FROM sys.database_principals WHERE name = 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G')  CREATE USER [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G] FOR LOGIN [NORTH_AMERICA\NA-1000-FIDO-APPDBA-G]

use regfieldtrials
go
-- add users to specific roles
EXEC sp_addrolemember 'db_FieldTrials_App', 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember 'db_datareader', 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember 'db_datawriter', 'ASIA-PACIFIC\AP-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember 'db_datawriter', 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember 'db_datareader', 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember 'db_FieldTrials_App', 'LAWA-SOUTH\LA-0000-FIDO-DB-DEVL-G'
EXEC sp_addrolemember 'db_FieldTrials_App', 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G'
EXEC sp_addrolemember 'db_datawriter', 'NORTH_AMERICA\NA-1000-FIDO-APP-Q-G'
EXEC sp_addrolemember 'db_datawriter', 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G'
EXEC sp_addrolemember 'db_owner', 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA-1000-FIDO-APPDBA-G'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G'
EXEC sp_addrolemember 'db_FieldTrials_App', 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G'
EXEC sp_addrolemember 'db_datawriter', 'NORTH_AMERICA\NA-1000-FIDO-SUPPORT-G'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L'
EXEC sp_addrolemember 'db_datawriter', 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L'
EXEC sp_addrolemember 'db_FieldTrials_App', 'NORTH_AMERICA\NA-1000-FIDO_DEVL-L'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA-1000-VICT-SUPPORT-G'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA-1000-VICT_RPTUSER-G'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA1000APP-FIDO2-P'
EXEC sp_addrolemember 'db_FieldTrials_App', 'NORTH_AMERICA\NA1000APP-FIDO2-P'
EXEC sp_addrolemember 'db_datawriter', 'NORTH_AMERICA\NA1000APP-FIDO2-P'
EXEC sp_addrolemember 'db_FieldTrials_App', 'NORTH_AMERICA\NA1000App_fidosync'
EXEC sp_addrolemember 'db_datareader', 'NORTH_AMERICA\NA1000App_fidosync'
EXEC sp_addrolemember 'db_datawriter', 'NORTH_AMERICA\NA1000App_fidosync'